baseURL: "https://anne-oceane.github.io"
title: oceane
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
googleAnalytics: G-BPP0V8EYY0

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        profileMode:
          enabled: true
          title: Océane Koffi
          imageUrl: "girl.png"
          # imageTitle: my image
          # imageWidth: 120
          # imageHeight: 120
          subtitle: "I am studying Data Science"
          buttons:
            - name: Blog
              url: posts
            - name: Project
              url: projects
            - name: CV
              url: /cv.pdf
        menu:
            main:
                - name: Home
                  url: "/"#
                  weight: 1
                - name: Blog
                  url: posts
                  weight: 2
                - name: Projects
                  url: projects
                  weight: 3
                - name: Connector
                  url: connector/
                  weight: 4
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10




outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Kanvaly website on AI"
    author: Kanvaly Fadiga
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowToc: true
    # comments: false
    images: ["cover.webp"]

    profileMode:
        enabled: false
        title: Kanvaly Fadiga
        imageUrl: "images/kanva.jpeg"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Kanvaly Fadiga"
        Content: >
            Hey friends. I am Kanvaly Fadiga. On this site we will talk about AI

    socialIcons:
        - name: github
          url: "https://github.com/fkanvaly"
        - name: linkedin
          url: "https://www.linkedin.com/in/kanvaly-fadiga/"

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

#     assets:
#         favicon: "images/kanva.jpeg"
#         favicon16x16: "<link / abs url>"
#         favicon32x32: "<link / abs url>"
#         apple_touch_icon: "<link / abs url>"
#         safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
     goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
